### ISSUE TITLE
[BUG] - tried it on my vayu but it didnt work halp me

### ISSUE THREAD

**Issue by gixousiyq** [n00b69/woa-alphaplus#1]
### Description

Trying to boot to adl but it shows recavery halp me ples

### Reproduction steps

```bash
卐卐卐卐
```

### Logs

```bash
Lorem ipsum dolor sit amet. Est voluptatem illo ut inventore molestiae non doloremque suscipit nam aliquam beatae id quae autem. Quo expedita nisi aut aliquid
```

### Agreement

- [X] I am using the latest Drivers.
- [X] I am running Windows 11 on the phone
- [X] There is no issue already describing my problem.

**Comment by n00b69** [comment]
Scull issue
